"$schema" = "https://raw.githubusercontent.com/nix-community/plasma-manager/refs/heads/trunk/plasma-manager/schema.json"

[[operations]]
operation = "write"
file = "kdeglobals"
group = "KDE"
xdg_directory = "config"
key = "SingleClick"
value = "false"

[[operations]]
operation = "write"
file = "kdeglobals"
group = "KDE"
xdg_directory = "config"
key = "AnimationDurationFactor"
value = "0.5"

[[operations]]
operation = "write"
file = "kwinrc"
group = "Effect-blur"
xdg_directory = "config"
key = "BlurStrength"
value = "10"

[[operations]]
operation = "write"
file = "kwinrc"
group = "Effect-blur"
xdg_directory = "config"
key = "NoiseStrength"
value = "0"

[[operations]]
operation = "write"
file = "kscreenlockerrc"
group = "Daemon"
xdg_directory = "config"
key = "LockGrace"
value = "5000"

[[operations]]
operation = "write"
file = "kcminputrc"
group = "Mouse"
xdg_directory = "config"
key = "cursorTheme"
value = "breeze_cursors"

