[package]
name = "plasma-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
etcetera = "0.8.0"
kconfig-rs = { path = "./kconfig-rs" }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"

[workspace]
members = [
  ".",
  "kconfig-rs"
]
